application: gifts-test
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: .*
  script: django_bootstrap.application

libraries:
- name: django
  version: "1.3"
- name: webapp2
  version: "2.5.2"
